### ISSUE TITLE
Tests fail thread sanitizer.

### ISSUE THREAD

**Issue by JodiTheTigger** [RichieSams/FiberTaskingLib#14]
Tried running the tests using the thread sanitizer and they failed in the calc triangles test.

However I don't know if these are false positives, or a genuine race condition.

1) edited root CMakeLists.txt
```set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11  -fsanitize=thread -fno-omit-frame-pointer")```
2) Edited TaskScheduler::Initialize to limit to two threads.
```m_numThreads = 2;//RAM: FTLGetNumHardwareThreads();```
3) created a 64 bit clang debug build (clang 3.6.2)
```CC=clang CXX=clang++ cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug"```

4) ran the test
``` test/FiberTaskingLib-test ```

Find shown below the output from the thread sanitizer's first two conflicts:

```==================
WARNING: ThreadSanitizer: data race (pid=17941)
  Read of size 8 at 0x7d6c0001f640 by thread T2:
    #0 std::_Hashtable<int, std::pair<int const, FiberTaskingLib::Fiber*>, std::allocator<std::pair<int const, FiberTaskingLib::Fiber*> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_bucket_index(int const&, unsigned long) const /usr/include/c++/5.2.0/bits/hashtable.h:621 (FiberTaskingLib-test+0x0000004f25ec)
    #1 std::__detail::_Map_base<int, std::pair<int const, FiberTaskingLib::Fiber*>, std::allocator<std::pair<int const, FiberTaskingLib::Fiber*> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::operator[](int&&) /usr/include/c++/5.2.0/bits/hashtable_policy.h:617 (FiberTaskingLib-test+0x0000004efd8a)
    #2 std::unordered_map<int, FiberTaskingLib::Fiber*, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, FiberTaskingLib::Fiber*> > >::operator[](int&&) /usr/include/c++/5.2.0/bits/unordered_map.h:672 (FiberTaskingLib-test+0x0000004edfd2)
    #3 FiberTaskingLib::TaskScheduler::ThreadStart(void*) ../source/fiber_tasking_lib/task_scheduler.cpp:38 (FiberTaskingLib-test+0x0000004eab98)

  Previous write of size 8 at 0x7d6c0001f640 by thread T1:
    [failed to restore the stack]

  Location is heap block of size 1688 at 0x7d6c0001f100 allocated by main thread:
    #0 operator new(unsigned long) /build/gcc-multilib/src/gcc-5.2.0/libsanitizer/tsan/tsan_interceptors.cc:571 (libtsan.so.0+0x000000025ef3)
    #1 FunctionalTests_CalcTriangleNum_Test::TestBody() ../test/calc_triangle_num.cpp:51 (FiberTaskingLib-test+0x00000048d14a)
    #2 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004cb4fa)
    #3 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004c2ad0)
    #4 testing::Test::Run() ../libs/gtest/src/gtest.cc:2437 (FiberTaskingLib-test+0x0000004a0f19)
    #5 testing::TestInfo::Run() ../libs/gtest/src/gtest.cc:2612 (FiberTaskingLib-test+0x0000004a18fd)
    #6 testing::TestCase::Run() ../libs/gtest/src/gtest.cc:2730 (FiberTaskingLib-test+0x0000004a2212)
    #7 testing::internal::UnitTestImpl::RunAllTests() ../libs/gtest/src/gtest.cc:4604 (FiberTaskingLib-test+0x0000004aa5b1)
    #8 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004ccc71)
    #9 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004c401e)
    #10 testing::UnitTest::Run() ../libs/gtest/src/gtest.cc:4222 (FiberTaskingLib-test+0x0000004a8c56)
    #11 RUN_ALL_TESTS() ../libs/gtest/include/gtest/gtest.h:2326 (FiberTaskingLib-test+0x00000048e752)
    #12 main ../test/main.cpp:16 (FiberTaskingLib-test+0x00000048e671)

  Thread T2 (tid=17944, running) created by main thread at:
    #0 pthread_create /build/gcc-multilib/src/gcc-5.2.0/libsanitizer/tsan/tsan_interceptors.cc:895 (libtsan.so.0+0x000000027a37)
    #1 FiberTaskingLib::FTLCreateThread(unsigned long*, unsigned int, void* (*)(void*), void*, unsigned long) ../source/fiber_tasking_lib/thread_abstraction.h:204 (FiberTaskingLib-test+0x0000004ec3a4)
    #2 FiberTaskingLib::TaskScheduler::Initialize(unsigned int, FiberTaskingLib::GlobalArgs*) ../source/fiber_tasking_lib/task_scheduler.cpp:186 (FiberTaskingLib-test+0x0000004eb841)
    #3 FunctionalTests_CalcTriangleNum_Test::TestBody() ../test/calc_triangle_num.cpp:52 (FiberTaskingLib-test+0x00000048d16e)
    #4 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004cb4fa)
    #5 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004c2ad0)
    #6 testing::Test::Run() ../libs/gtest/src/gtest.cc:2437 (FiberTaskingLib-test+0x0000004a0f19)
    #7 testing::TestInfo::Run() ../libs/gtest/src/gtest.cc:2612 (FiberTaskingLib-test+0x0000004a18fd)
    #8 testing::TestCase::Run() ../libs/gtest/src/gtest.cc:2730 (FiberTaskingLib-test+0x0000004a2212)
    #9 testing::internal::UnitTestImpl::RunAllTests() ../libs/gtest/src/gtest.cc:4604 (FiberTaskingLib-test+0x0000004aa5b1)
    #10 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004ccc71)
    #11 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004c401e)
    #12 testing::UnitTest::Run() ../libs/gtest/src/gtest.cc:4222 (FiberTaskingLib-test+0x0000004a8c56)
    #13 RUN_ALL_TESTS() ../libs/gtest/include/gtest/gtest.h:2326 (FiberTaskingLib-test+0x00000048e752)
    #14 main ../test/main.cpp:16 (FiberTaskingLib-test+0x00000048e671)

  Thread T1 (tid=17943, running) created by main thread at:
    #0 pthread_create /build/gcc-multilib/src/gcc-5.2.0/libsanitizer/tsan/tsan_interceptors.cc:895 (libtsan.so.0+0x000000027a37)
    #1 FiberTaskingLib::FTLCreateThread(unsigned long*, unsigned int, void* (*)(void*), void*, unsigned long) ../source/fiber_tasking_lib/thread_abstraction.h:204 (FiberTaskingLib-test+0x0000004ec3a4)
    #2 FiberTaskingLib::TaskScheduler::Initialize(unsigned int, FiberTaskingLib::GlobalArgs*) ../source/fiber_tasking_lib/task_scheduler.cpp:186 (FiberTaskingLib-test+0x0000004eb841)
    #3 FunctionalTests_CalcTriangleNum_Test::TestBody() ../test/calc_triangle_num.cpp:52 (FiberTaskingLib-test+0x00000048d16e)
    #4 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004cb4fa)
    #5 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004c2ad0)
    #6 testing::Test::Run() ../libs/gtest/src/gtest.cc:2437 (FiberTaskingLib-test+0x0000004a0f19)
    #7 testing::TestInfo::Run() ../libs/gtest/src/gtest.cc:2612 (FiberTaskingLib-test+0x0000004a18fd)
    #8 testing::TestCase::Run() ../libs/gtest/src/gtest.cc:2730 (FiberTaskingLib-test+0x0000004a2212)
    #9 testing::internal::UnitTestImpl::RunAllTests() ../libs/gtest/src/gtest.cc:4604 (FiberTaskingLib-test+0x0000004aa5b1)
    #10 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004ccc71)
    #11 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004c401e)
    #12 testing::UnitTest::Run() ../libs/gtest/src/gtest.cc:4222 (FiberTaskingLib-test+0x0000004a8c56)
    #13 RUN_ALL_TESTS() ../libs/gtest/include/gtest/gtest.h:2326 (FiberTaskingLib-test+0x00000048e752)
    #14 main ../test/main.cpp:16 (FiberTaskingLib-test+0x00000048e671)

SUMMARY: ThreadSanitizer: data race /usr/include/c++/5.2.0/bits/hashtable.h:621 std::_Hashtable<int, std::pair<int const, FiberTaskingLib::Fiber*>, std::allocator<std::pair<int const, FiberTaskingLib::Fiber*> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_bucket_index(int const&, unsigned long) const
==================
==================
WARNING: ThreadSanitizer: data race (pid=17941)
  Read of size 8 at 0x7d6c0001f638 by thread T3:
    #0 std::_Hashtable<int, std::pair<int const, FiberTaskingLib::Fiber*>, std::allocator<std::pair<int const, FiberTaskingLib::Fiber*> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node(unsigned long, int const&, unsigned long) const <null> (FiberTaskingLib-test+0x0000004f5a72)
    #1 std::_Hashtable<int, std::pair<int const, FiberTaskingLib::Fiber*>, std::allocator<std::pair<int const, FiberTaskingLib::Fiber*> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_node(unsigned long, int const&, unsigned long) const /usr/include/c++/5.2.0/bits/hashtable.h:632 (FiberTaskingLib-test+0x0000004f266c)
    #2 std::__detail::_Map_base<int, std::pair<int const, FiberTaskingLib::Fiber*>, std::allocator<std::pair<int const, FiberTaskingLib::Fiber*> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::operator[](int&&) /usr/include/c++/5.2.0/bits/hashtable_policy.h:618 (FiberTaskingLib-test+0x0000004efda6)
    #3 std::unordered_map<int, FiberTaskingLib::Fiber*, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, FiberTaskingLib::Fiber*> > >::operator[](int&&) /usr/include/c++/5.2.0/bits/unordered_map.h:672 (FiberTaskingLib-test+0x0000004edfd2)
    #4 FiberTaskingLib::TaskScheduler::ThreadStart(void*) ../source/fiber_tasking_lib/task_scheduler.cpp:38 (FiberTaskingLib-test+0x0000004eab98)

  Previous write of size 8 at 0x7d6c0001f638 by thread T1:
    [failed to restore the stack]

  Location is heap block of size 1688 at 0x7d6c0001f100 allocated by main thread:
    #0 operator new(unsigned long) /build/gcc-multilib/src/gcc-5.2.0/libsanitizer/tsan/tsan_interceptors.cc:571 (libtsan.so.0+0x000000025ef3)
    #1 FunctionalTests_CalcTriangleNum_Test::TestBody() ../test/calc_triangle_num.cpp:51 (FiberTaskingLib-test+0x00000048d14a)
    #2 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004cb4fa)
    #3 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004c2ad0)
    #4 testing::Test::Run() ../libs/gtest/src/gtest.cc:2437 (FiberTaskingLib-test+0x0000004a0f19)
    #5 testing::TestInfo::Run() ../libs/gtest/src/gtest.cc:2612 (FiberTaskingLib-test+0x0000004a18fd)
    #6 testing::TestCase::Run() ../libs/gtest/src/gtest.cc:2730 (FiberTaskingLib-test+0x0000004a2212)
    #7 testing::internal::UnitTestImpl::RunAllTests() ../libs/gtest/src/gtest.cc:4604 (FiberTaskingLib-test+0x0000004aa5b1)
    #8 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004ccc71)
    #9 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004c401e)
    #10 testing::UnitTest::Run() ../libs/gtest/src/gtest.cc:4222 (FiberTaskingLib-test+0x0000004a8c56)
    #11 RUN_ALL_TESTS() ../libs/gtest/include/gtest/gtest.h:2326 (FiberTaskingLib-test+0x00000048e752)
    #12 main ../test/main.cpp:16 (FiberTaskingLib-test+0x00000048e671)

  Thread T3 (tid=17945, running) created by main thread at:
    #0 pthread_create /build/gcc-multilib/src/gcc-5.2.0/libsanitizer/tsan/tsan_interceptors.cc:895 (libtsan.so.0+0x000000027a37)
    #1 FiberTaskingLib::FTLCreateThread(unsigned long*, unsigned int, void* (*)(void*), void*, unsigned long) ../source/fiber_tasking_lib/thread_abstraction.h:204 (FiberTaskingLib-test+0x0000004ec3a4)
    #2 FiberTaskingLib::TaskScheduler::Initialize(unsigned int, FiberTaskingLib::GlobalArgs*) ../source/fiber_tasking_lib/task_scheduler.cpp:186 (FiberTaskingLib-test+0x0000004eb841)
    #3 FunctionalTests_CalcTriangleNum_Test::TestBody() ../test/calc_triangle_num.cpp:52 (FiberTaskingLib-test+0x00000048d16e)
    #4 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004cb4fa)
    #5 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004c2ad0)
    #6 testing::Test::Run() ../libs/gtest/src/gtest.cc:2437 (FiberTaskingLib-test+0x0000004a0f19)
    #7 testing::TestInfo::Run() ../libs/gtest/src/gtest.cc:2612 (FiberTaskingLib-test+0x0000004a18fd)
    #8 testing::TestCase::Run() ../libs/gtest/src/gtest.cc:2730 (FiberTaskingLib-test+0x0000004a2212)
    #9 testing::internal::UnitTestImpl::RunAllTests() ../libs/gtest/src/gtest.cc:4604 (FiberTaskingLib-test+0x0000004aa5b1)
    #10 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004ccc71)
    #11 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004c401e)
    #12 testing::UnitTest::Run() ../libs/gtest/src/gtest.cc:4222 (FiberTaskingLib-test+0x0000004a8c56)
    #13 RUN_ALL_TESTS() ../libs/gtest/include/gtest/gtest.h:2326 (FiberTaskingLib-test+0x00000048e752)
    #14 main ../test/main.cpp:16 (FiberTaskingLib-test+0x00000048e671)

  Thread T1 (tid=17943, running) created by main thread at:
    #0 pthread_create /build/gcc-multilib/src/gcc-5.2.0/libsanitizer/tsan/tsan_interceptors.cc:895 (libtsan.so.0+0x000000027a37)
    #1 FiberTaskingLib::FTLCreateThread(unsigned long*, unsigned int, void* (*)(void*), void*, unsigned long) ../source/fiber_tasking_lib/thread_abstraction.h:204 (FiberTaskingLib-test+0x0000004ec3a4)
    #2 FiberTaskingLib::TaskScheduler::Initialize(unsigned int, FiberTaskingLib::GlobalArgs*) ../source/fiber_tasking_lib/task_scheduler.cpp:186 (FiberTaskingLib-test+0x0000004eb841)
    #3 FunctionalTests_CalcTriangleNum_Test::TestBody() ../test/calc_triangle_num.cpp:52 (FiberTaskingLib-test+0x00000048d16e)
    #4 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004cb4fa)
    #5 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004c2ad0)
    #6 testing::Test::Run() ../libs/gtest/src/gtest.cc:2437 (FiberTaskingLib-test+0x0000004a0f19)
    #7 testing::TestInfo::Run() ../libs/gtest/src/gtest.cc:2612 (FiberTaskingLib-test+0x0000004a18fd)
    #8 testing::TestCase::Run() ../libs/gtest/src/gtest.cc:2730 (FiberTaskingLib-test+0x0000004a2212)
    #9 testing::internal::UnitTestImpl::RunAllTests() ../libs/gtest/src/gtest.cc:4604 (FiberTaskingLib-test+0x0000004aa5b1)
    #10 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004ccc71)
    #11 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x0000004c401e)
    #12 testing::UnitTest::Run() ../libs/gtest/src/gtest.cc:4222 (FiberTaskingLib-test+0x0000004a8c56)
    #13 RUN_ALL_TESTS() ../libs/gtest/include/gtest/gtest.h:2326 (FiberTaskingLib-test+0x00000048e752)
    #14 main ../test/main.cpp:16 (FiberTaskingLib-test+0x00000048e671)

SUMMARY: ThreadSanitizer: data race ??:0 std::_Hashtable<int, std::pair<int const, FiberTaskingLib::Fiber*>, std::allocator<std::pair<int const, FiberTaskingLib::Fiber*> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_find_before_node(unsigned long, int const&, unsigned long) const
==================
```

**Comment by RichieSams** [comment]
The error points to:
    globalArgs->g_taskScheduler.m_fiberSwitchingFibers[FTLGetCurrentThreadId()]

A data race would mean FTLGetCurrentThreadId is not functioning properly. ie. it is returning the same value for two different threads. Hmmm. Looking into it

**Comment by RichieSams** [comment]
As an aside, if you remove the CalcTriangles test (ie. comment out calc_triangle_num.cpp in test/CMakeLists.txt), do the tests pass?

**Comment by JodiTheTigger** [comment]
Yes it still crashes (see answer given in Issue #13). And it still has tsan issues as well.

**Comment by JodiTheTigger** [comment]
So I decided to have another stab at this one. Basically it's complaining about:
`TaskScheduler::ThreadStart()`
```cpp
	globalArgs->g_taskScheduler.m_counterWaitingFibers[FTLGetCurrentThreadId()] = FTLCreateFiber(FTL_HELPER_FIBER_STACK_SIZE, CounterWaitStart, reinterpret_cast<fiber_arg_t>(&globalArgs->g_taskScheduler));

```
clashing with
`TaskScheduler::WaitForCounter()`
```cpp
	FTLSwitchToFiber(currentFiber, m_counterWaitingFibers[FTLGetCurrentThreadId()]);
```
I noticed that 

TaskScheduler::ThreadStart has 
`globalArgs->g_taskScheduler.m_waitingTaskLock.lock();`
before it accessed m_fiberSwitchingFibers or m_counterWaitingFibers

but `TaskScheduler::WaitForCounter()` doesn't.

So I tried wrapping it inside a lock, and the warnings went away (however I still get the other linux segfault #13 ).

```cpp
    m_waitingTaskLock.lock();
    auto waiting_fiber = m_counterWaitingFibers[FTLGetCurrentThreadId()];
    m_waitingTaskLock.unlock();

    FTLSwitchToFiber(currentFiber, waiting_fiber);
```
So if that lock makes sense to you, then it looks like this will fix the thread race.

**Comment by RichieSams** [comment]
This should be fixed by commits 1837d45e152e9bf2742248f127434dfad7e118d8 to 013ee8cabd4ab39226e0aeb6c492b9a025ea2cc3

**Comment by JodiTheTigger** [comment]
Ok, I don't get crashes anymore. However I still get tsan errors (both in gcc and clang).

As usual, I change the build flags, did a debug build and limited the thread count to 2. Here is the first error I got:

```
WARNING: ThreadSanitizer: data race (pid=19322)
  Read of size 8 at 0x7d8c0000e640 by thread T1:
    #0 FiberTaskingLib::TaskScheduler::FiberStart(long) ../source/task_scheduler.cpp:96 (FiberTaskingLib-test+0x000000443700)
    #1 make_fcontext <null> (FiberTaskingLib-test+0x000000447890)
    #2 Producer(FiberTaskingLib::TaskScheduler*, void*) ../tests/producer_consumer/producer_consumer.cpp:36 (FiberTaskingLib-test+0x00000041e5be)
    #3 FiberTaskingLib::TaskScheduler::FiberStart(long) ../source/task_scheduler.cpp:125 (FiberTaskingLib-test+0x000000443995)
    #4 make_fcontext <null> (FiberTaskingLib-test+0x000000447890)
    #5 Producer(FiberTaskingLib::TaskScheduler*, void*) ../tests/producer_consumer/producer_consumer.cpp:36 (FiberTaskingLib-test+0x00000041e5be)
    #6 FiberTaskingLib::TaskScheduler::FiberStart(long) ../source/task_scheduler.cpp:125 (FiberTaskingLib-test+0x000000443995)

    <snip>

    #143 Producer(FiberTaskingLib::TaskScheduler*, void*) ../tests/producer_consumer/producer_consumer.cpp:36 (FiberTaskingLib-test+0x00000041e5be)
    #144 FiberTaskingLib::TaskScheduler::FiberStart(long) ../source/task_scheduler.cpp:125 (FiberTaskingLib-test+0x000000443995)
    #145 make_fcontext <null> (FiberTaskingLib-test+0x000000447890)
    #146 Producer(FiberTaskingLib::TaskScheduler*, void*) ../tests/producer_consumer/producer_consumer.cpp:36 (FiberTaskingLib-test+0x00000041e5be)
    #147 FiberTaskingLib::TaskScheduler::FiberStart(long) ../source/task_scheduler.cpp:125 (FiberTaskingLib-test+0x000000443995)
    #148 make_fcontext <null> (FiberTaskingLib-test+0x000000447890)

  Previous write of size 8 at 0x7d8c0000e640 by main thread:
    [failed to restore the stack]

  Location is heap block of size 6400 at 0x7d8c0000e000 allocated by main thread:
    #0 operator new(unsigned long) /build/gcc-multilib/src/gcc/libsanitizer/tsan/tsan_new_delete.cc:43 (libtsan.so.0+0x000000069f73)
    #1 __gnu_cxx::new_allocator<FiberTaskingLib::TaskScheduler::WaitingBundle>::allocate(unsigned long, void const*) /usr/include/c++/6.2.1/ext/new_allocator.h:104 (FiberTaskingLib-test+0x0000004469de)
    #2 std::allocator_traits<std::allocator<FiberTaskingLib::TaskScheduler::WaitingBundle> >::allocate(std::allocator<FiberTaskingLib::TaskScheduler::WaitingBundle>&, unsigned long) /usr/include/c++/6.2.1/bits/alloc_traits.h:416 (FiberTaskingLib-test+0x0000004469de)
    #3 std::_Vector_base<FiberTaskingLib::TaskScheduler::WaitingBundle, std::allocator<FiberTaskingLib::TaskScheduler::WaitingBundle> >::_M_allocate(unsigned long) /usr/include/c++/6.2.1/bits/stl_vector.h:170 (FiberTaskingLib-test+0x0000004469de)
    #4 std::vector<FiberTaskingLib::TaskScheduler::WaitingBundle, std::allocator<FiberTaskingLib::TaskScheduler::WaitingBundle> >::_M_default_append(unsigned long) /usr/include/c++/6.2.1/bits/vector.tcc:557 (FiberTaskingLib-test+0x0000004469de)
    #5 std::vector<FiberTaskingLib::TaskScheduler::WaitingBundle, std::allocator<FiberTaskingLib::TaskScheduler::WaitingBundle> >::resize(unsigned long) /usr/include/c++/6.2.1/bits/stl_vector.h:677 (FiberTaskingLib-test+0x000000444601)
    #6 FiberTaskingLib::TaskScheduler::Run(unsigned int, void (*)(FiberTaskingLib::TaskScheduler*, void*), void*) ../source/task_scheduler.cpp:169 (FiberTaskingLib-test+0x000000444601)
    #7 FunctionalTests_ProducerConsumer_Test::TestBody() ../tests/producer_consumer/producer_consumer.cpp:64 (FiberTaskingLib-test+0x00000041e4e8)
    #8 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ../third_party/gtest/src/gtest.cc:2402 (FiberTaskingLib-test+0x000000441813)

    <snip>
    
    #18 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ../third_party/gtest/src/gtest.cc:2438 (FiberTaskingLib-test+0x000000441813)
    #19 __libc_start_main <null> (libc.so.6+0x000000020290)

  Thread T1 (tid=19324, running) created by main thread at:
    #0 pthread_create /build/gcc-multilib/src/gcc/libsanitizer/tsan/tsan_interceptors.cc:876 (libtsan.so.0+0x000000028470)
    #1 FiberTaskingLib::FTLCreateThread(unsigned int, void* (*)(void*), void*, unsigned long, unsigned long*) ../source/../include/fiber_tasking_lib/thread_abstraction.h:267 (FiberTaskingLib-test+0x00000044443d)
    #2 FiberTaskingLib::TaskScheduler::Run(unsigned int, void (*)(FiberTaskingLib::TaskScheduler*, void*), void*) ../source/task_scheduler.cpp:189 (FiberTaskingLib-test+0x00000044443d)
    #3 FunctionalTests_ProducerConsumer_Test::TestBody() ../tests/producer_consumer/producer_consumer.cpp:64 (FiberTaskingLib-test+0x00000041e4e8)
    #4 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ../third_party/gtest/src/gtest.cc:2402 (FiberTaskingLib-test+0x000000441813)
    #5 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ../third_party/gtest/src/gtest.cc:2438 (FiberTaskingLib-test+0x000000441813)
    #6 make_fcontext <null> (FiberTaskingLib-test+0x000000447890)
    #7 make_fcontext <null> (FiberTaskingLib-test+0x000000447890)
    #8 make_fcontext <null> (FiberTaskingLib-test+0x000000447890)
    #9 make_fcontext <null> (FiberTaskingLib-test+0x000000447890)
    #10 make_fcontext <null> (FiberTaskingLib-test+0x000000447890)
    #11 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ../third_party/gtest/src/gtest.cc:2402 (FiberTaskingLib-test+0x000000441813)
    #12 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ../third_party/gtest/src/gtest.cc:2438 (FiberTaskingLib-test+0x000000441813)
    #13 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ../third_party/gtest/src/gtest.cc:2402 (FiberTaskingLib-test+0x000000441813)
    #14 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ../third_party/gtest/src/gtest.cc:2438 (FiberTaskingLib-test+0x000000441813)
    #15 __libc_start_main <null> (libc.so.6+0x000000020290)

SUMMARY: ThreadSanitizer: data race ../source/task_scheduler.cpp:96 in FiberTaskingLib::TaskScheduler::FiberStart(long)

```

**Comment by RichieSams** [comment]
I don't understand why tsan thinks this is a data race.

m_waitingBundles is effectively locked by m_waitingFibers. m_waitingFibers isn't set until m_waitingBundles is filled, so the check at line#96 will only happen if m_waitingBundles is filled. 

Any comments?

**Comment by RichieSams** [comment]
I'm getting this:

WARNING: ThreadSanitizer: data race (pid=6753)
  Write of size 8 at 0x7d040000f6b0 by thread T3:
    #0 operator delete(void*) <null> (FiberTaskingLib-test+0x0000004f0139)
    #1 std::_Sp_counted_ptr<std::atomic<unsigned int>*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() <null> (FiberTaskingLib-test+0x000000563ee8)
    #2 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() <null> (FiberTaskingLib-test+0x0000004f6eaf)
    #3 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() <null> (FiberTaskingLib-test+0x0000004f6e38)
    #4 std::__shared_ptr<std::atomic<unsigned int>, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() <null> (FiberTaskingLib-test+0x0000004f6dcc)
    #5 std::shared_ptr<std::atomic<unsigned int> >::~shared_ptr() <null> (FiberTaskingLib-test+0x0000004f6c08)
    #6 TriangleNumberMainTask(FiberTaskingLib::TaskScheduler*, void*) <null> (FiberTaskingLib-test+0x0000004f7c9d)
    #7 FiberTaskingLib::TaskScheduler::ThreadStart(void*) <null> (FiberTaskingLib-test+0x00000055a5f2)

  Previous atomic read of size 4 at 0x7d040000f6b0 by thread T1:
    [failed to restore the stack]

  Thread T3 (tid=6757, running) created by main thread at:
    #0 pthread_create <null> (FiberTaskingLib-test+0x000000470156)
    #1 FiberTaskingLib::FTLCreateThread(unsigned int, void* (*)(void*), void*, unsigned long, unsigned long*) <null> (FiberTaskingLib-test+0x00000055d992)
    #2 FiberTaskingLib::TaskScheduler::Run(unsigned int, void (*)(FiberTaskingLib::TaskScheduler*, void*), void*) <null> (FiberTaskingLib-test+0x00000055bc9b)
    #3 FunctionalTests_CalcTriangleNum_Test::TestBody() <null> (FiberTaskingLib-test+0x0000004f7d45)
    #4 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x00000054c942)
    #5 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x000000528fba)
    #6 testing::Test::Run() <null> (FiberTaskingLib-test+0x000000505b51)
    #7 testing::TestInfo::Run() <null> (FiberTaskingLib-test+0x000000506bdf)
    #8 testing::TestCase::Run() <null> (FiberTaskingLib-test+0x000000507540)
    #9 testing::internal::UnitTestImpl::RunAllTests() <null> (FiberTaskingLib-test+0x0000005118b1)
    #10 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x000000552772)
    #11 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x00000052c96a)
    #12 testing::UnitTest::Run() <null> (FiberTaskingLib-test+0x0000005113cf)
    #13 RUN_ALL_TESTS() <null> (FiberTaskingLib-test+0x0000004f228d)
    #14 main <null> (FiberTaskingLib-test+0x0000004f224d)

  Thread T1 (tid=6755, running) created by main thread at:
    #0 pthread_create <null> (FiberTaskingLib-test+0x000000470156)
    #1 FiberTaskingLib::FTLCreateThread(unsigned int, void* (*)(void*), void*, unsigned long, unsigned long*) <null> (FiberTaskingLib-test+0x00000055d992)
    #2 FiberTaskingLib::TaskScheduler::Run(unsigned int, void (*)(FiberTaskingLib::TaskScheduler*, void*), void*) <null> (FiberTaskingLib-test+0x00000055bc9b)
    #3 FunctionalTests_CalcTriangleNum_Test::TestBody() <null> (FiberTaskingLib-test+0x0000004f7d45)
    #4 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x00000054c942)
    #5 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x000000528fba)
    #6 testing::Test::Run() <null> (FiberTaskingLib-test+0x000000505b51)
    #7 testing::TestInfo::Run() <null> (FiberTaskingLib-test+0x000000506bdf)
    #8 testing::TestCase::Run() <null> (FiberTaskingLib-test+0x000000507540)
    #9 testing::internal::UnitTestImpl::RunAllTests() <null> (FiberTaskingLib-test+0x0000005118b1)
    #10 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x000000552772)
    #11 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x00000052c96a)
    #12 testing::UnitTest::Run() <null> (FiberTaskingLib-test+0x0000005113cf)
    #13 RUN_ALL_TESTS() <null> (FiberTaskingLib-test+0x0000004f228d)
    #14 main <null> (FiberTaskingLib-test+0x0000004f224d)

SUMMARY: ThreadSanitizer: data race (/media/sf_FiberTaskingLib/build_ubuntu/tests/FiberTaskingLib-test+0x4f0139) in operator delete(void*)
==================

**Comment by RichieSams** [comment]
I'm getting this:

```
WARNING: ThreadSanitizer: data race (pid=6753)
  Write of size 8 at 0x7d040000f6b0 by thread T3:
    #0 operator delete(void*) <null> (FiberTaskingLib-test+0x0000004f0139)
    #1 std::_Sp_counted_ptr<std::atomic<unsigned int>*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() <null> (FiberTaskingLib-test+0x000000563ee8)
    #2 std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() <null> (FiberTaskingLib-test+0x0000004f6eaf)
    #3 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() <null> (FiberTaskingLib-test+0x0000004f6e38)
    #4 std::__shared_ptr<std::atomic<unsigned int>, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() <null> (FiberTaskingLib-test+0x0000004f6dcc)
    #5 std::shared_ptr<std::atomic<unsigned int> >::~shared_ptr() <null> (FiberTaskingLib-test+0x0000004f6c08)
    #6 TriangleNumberMainTask(FiberTaskingLib::TaskScheduler*, void*) <null> (FiberTaskingLib-test+0x0000004f7c9d)
    #7 FiberTaskingLib::TaskScheduler::ThreadStart(void*) <null> (FiberTaskingLib-test+0x00000055a5f2)

  Previous atomic read of size 4 at 0x7d040000f6b0 by thread T1:
    [failed to restore the stack]

  Thread T3 (tid=6757, running) created by main thread at:
    #0 pthread_create <null> (FiberTaskingLib-test+0x000000470156)
    #1 FiberTaskingLib::FTLCreateThread(unsigned int, void* (*)(void*), void*, unsigned long, unsigned long*) <null> (FiberTaskingLib-test+0x00000055d992)
    #2 FiberTaskingLib::TaskScheduler::Run(unsigned int, void (*)(FiberTaskingLib::TaskScheduler*, void*), void*) <null> (FiberTaskingLib-test+0x00000055bc9b)
    #3 FunctionalTests_CalcTriangleNum_Test::TestBody() <null> (FiberTaskingLib-test+0x0000004f7d45)
    #4 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x00000054c942)
    #5 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x000000528fba)
    #6 testing::Test::Run() <null> (FiberTaskingLib-test+0x000000505b51)
    #7 testing::TestInfo::Run() <null> (FiberTaskingLib-test+0x000000506bdf)
    #8 testing::TestCase::Run() <null> (FiberTaskingLib-test+0x000000507540)
    #9 testing::internal::UnitTestImpl::RunAllTests() <null> (FiberTaskingLib-test+0x0000005118b1)
    #10 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x000000552772)
    #11 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x00000052c96a)
    #12 testing::UnitTest::Run() <null> (FiberTaskingLib-test+0x0000005113cf)
    #13 RUN_ALL_TESTS() <null> (FiberTaskingLib-test+0x0000004f228d)
    #14 main <null> (FiberTaskingLib-test+0x0000004f224d)

  Thread T1 (tid=6755, running) created by main thread at:
    #0 pthread_create <null> (FiberTaskingLib-test+0x000000470156)
    #1 FiberTaskingLib::FTLCreateThread(unsigned int, void* (*)(void*), void*, unsigned long, unsigned long*) <null> (FiberTaskingLib-test+0x00000055d992)
    #2 FiberTaskingLib::TaskScheduler::Run(unsigned int, void (*)(FiberTaskingLib::TaskScheduler*, void*), void*) <null> (FiberTaskingLib-test+0x00000055bc9b)
    #3 FunctionalTests_CalcTriangleNum_Test::TestBody() <null> (FiberTaskingLib-test+0x0000004f7d45)
    #4 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x00000054c942)
    #5 void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (FiberTaskingLib-test+0x000000528fba)
    #6 testing::Test::Run() <null> (FiberTaskingLib-test+0x000000505b51)
    #7 testing::TestInfo::Run() <null> (FiberTaskingLib-test+0x000000506bdf)
    #8 testing::TestCase::Run() <null> (FiberTaskingLib-test+0x000000507540)
    #9 testing::internal::UnitTestImpl::RunAllTests() <null> (FiberTaskingLib-test+0x0000005118b1)
    #10 bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x000000552772)
    #11 bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) <null> (FiberTaskingLib-test+0x00000052c96a)
    #12 testing::UnitTest::Run() <null> (FiberTaskingLib-test+0x0000005113cf)
    #13 RUN_ALL_TESTS() <null> (FiberTaskingLib-test+0x0000004f228d)
    #14 main <null> (FiberTaskingLib-test+0x0000004f224d)

SUMMARY: ThreadSanitizer: data race (/media/sf_FiberTaskingLib/build_ubuntu/tests/FiberTaskingLib-test+0x4f0139) in operator delete(void*)
==================

```

**Comment by JodiTheTigger** [comment]
Oh hey, I generate a ton of warnings in sewing with tsan as well (lol, my stack is 47000 deep). Bugger. 

Oooh, when I run as C++11 I even trigger an unreachable code assert.

Ok, my attitude is that with tsan, it cannot handle the context switching that we use.
So you'll have to ignore it for now.

Maybe aim for valgrind clean? (remember you need to do intrusive valgrind changes for fcontext).

The thing with thread and data races, I'm never 100% confident that I've eliminated them. I just run my test code for hours and hope it never fails, triggers an assert, or leaks memory.

**Comment by RichieSams** [comment]
Data races are so hard to test for..... :( But I agree that the tsan seems to be a false positive. 

Adding valgrind support is on my short term goals. I want to replace the abominable task queue first.
